### ISSUE TITLE
Record every cage change for every mouse

### ISSUE THREAD

**Issue by cxrodgers** [cxrodgers/HeroMouseColony#10]
Probably, every time the cage attribute is changed, this triggers the creation of a "CageChange" model, which is associated with this mouse. These CageChanges are displayed in an inline at the bottom of the mouse page, along with the date/time this was entered into the database.

Even better, if it's in an inline, we can delete erroneous cage changes, and change the date/time field if necessary (for instance, you forgot to input the cage change for a couple days after it happened).

Even better, can we also view from the Cage page all Mouse that have ever been in that cage and at what times? Seems like it should be a straightforward reversal of the above relation?

So "CageChange" will have FK to Mouse, CageBefore, and CageAfter (I think?)

**Comment by danieldkato** [comment]
I think that's right - since CageChange will have FKs to Cage (which will require reverse search names, because there are multiple FKs to the same model), we can invoke the reverse search name from a Cage object to get all CageChange objects associated with that Cage, then in turn get all mice associated with those CageChange objects, and the dates of the changes to infer when the mice were in the Cage.

**Comment by danieldkato** [comment]
Come to think of it, maybe the simplest way to write this model would be to have one FK to a Cage and one DateField, which would store the date on which the mouse was put in the cage. 

For new pups, maybe we could define a custom save method on Cage or Litter (or their admins) that automatically creates a CageChange object for every newly created Mouse, and automatically sets the Cage to the cage of birth and the date to date of birth.

**Comment by cxrodgers** [comment]
Implemented using django_simple_history
